name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PyPI
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: bash infrastructure/scripts/install_dependencies.sh
    
    - name: Build packages
      run: bash infrastructure/scripts/build_packages.sh
    
    - name: Publish backend package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: src/backend/dist/
    
    - name: Publish web UI package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: src/web/dist/